# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 2,12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS }}

          # Options
          user: lucasepe
          template: classic
          base: activity, community, repositories
          config_timezone: Europe/Italy
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: stars
          plugin_topics_limit: 5
